# Generated by Django 4.1.1 on 2022-09-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_dni_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.TextField(max_length=400),
        ),
    ]
