# Generated by Django 4.1.1 on 2022-10-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
