# Generated by Django 4.1.1 on 2022-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_detail_product_title_alter_orders_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_mail',
            field=models.CharField(default=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.IntegerField(default=False, max_length=2),
        ),
    ]
