# Generated by Django 4.1.1 on 2022-10-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orders_user_mail_alter_orders_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='materia',
            field=models.CharField(max_length=50),
        ),
    ]
