# Generated by Django 4.1.1 on 2022-11-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_products_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
