# Generated by Django 4.1.1 on 2022-11-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orders_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='anillado',
            field=models.BooleanField(default=False),
        ),
    ]
