# Generated by Django 4.1.1 on 2022-11-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_orders_anillado_order_detail_anillado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='anillado',
            field=models.IntegerField(),
        ),
    ]
